-- Add created_by and updated_by columns
ALTER TABLE users ADD COLUMN created_by INTEGER NULL;
ALTER TABLE users ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE surgeries ADD COLUMN created_by INTEGER NULL;
ALTER TABLE surgeries ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE appointments ADD COLUMN created_by INTEGER NULL;
ALTER TABLE appointments ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE photo_album_types ADD COLUMN created_by INTEGER NULL;
ALTER TABLE photo_album_types ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE patient_photos ADD COLUMN created_by INTEGER NULL;
ALTER TABLE patient_photos ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE agencies ADD COLUMN created_by INTEGER NULL;
ALTER TABLE agencies ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE invitations ADD COLUMN created_by INTEGER NULL;
ALTER TABLE invitations ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE rooms ADD COLUMN created_by INTEGER NULL;
ALTER TABLE rooms ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE room_reservations ADD COLUMN created_by INTEGER NULL;
ALTER TABLE room_reservations ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE staff ADD COLUMN created_by INTEGER NULL;
ALTER TABLE staff ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE staff_details ADD COLUMN created_by INTEGER NULL;
ALTER TABLE staff_details ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE staff_availability ADD COLUMN created_by INTEGER NULL;
ALTER TABLE staff_availability ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE surgery_staff ADD COLUMN created_by INTEGER NULL;
ALTER TABLE surgery_staff ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE procedures ADD COLUMN created_by INTEGER NULL;
ALTER TABLE procedures ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE settings ADD COLUMN created_by INTEGER NULL;
ALTER TABLE settings ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE emails ADD COLUMN created_by INTEGER NULL;
ALTER TABLE emails ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE user_email_settings ADD COLUMN created_by INTEGER NULL;
ALTER TABLE user_email_settings ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE email_attachments ADD COLUMN created_by INTEGER NULL;
ALTER TABLE email_attachments ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE messages ADD COLUMN created_by INTEGER NULL;
ALTER TABLE messages ADD COLUMN updated_by INTEGER NULL;
ALTER TABLE message_reactions ADD COLUMN created_by INTEGER NULL;
ALTER TABLE message_reactions ADD COLUMN updated_by INTEGER NULL;

-- Add foreign key constraints
ALTER TABLE users ADD CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE surgeries ADD CONSTRAINT fk_surgeries_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE surgeries ADD CONSTRAINT fk_surgeries_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE photo_album_types ADD CONSTRAINT fk_photo_album_types_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE photo_album_types ADD CONSTRAINT fk_photo_album_types_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE patient_photos ADD CONSTRAINT fk_patient_photos_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE patient_photos ADD CONSTRAINT fk_patient_photos_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE agencies ADD CONSTRAINT fk_agencies_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE agencies ADD CONSTRAINT fk_agencies_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE invitations ADD CONSTRAINT fk_invitations_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE invitations ADD CONSTRAINT fk_invitations_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE rooms ADD CONSTRAINT fk_rooms_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE rooms ADD CONSTRAINT fk_rooms_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE room_reservations ADD CONSTRAINT fk_room_reservations_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE room_reservations ADD CONSTRAINT fk_room_reservations_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE staff ADD CONSTRAINT fk_staff_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE staff ADD CONSTRAINT fk_staff_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE staff_details ADD CONSTRAINT fk_staff_details_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE staff_details ADD CONSTRAINT fk_staff_details_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE staff_availability ADD CONSTRAINT fk_staff_availability_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE staff_availability ADD CONSTRAINT fk_staff_availability_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE surgery_staff ADD CONSTRAINT fk_surgery_staff_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE surgery_staff ADD CONSTRAINT fk_surgery_staff_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE procedures ADD CONSTRAINT fk_procedures_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE procedures ADD CONSTRAINT fk_procedures_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE settings ADD CONSTRAINT fk_settings_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE settings ADD CONSTRAINT fk_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE emails ADD CONSTRAINT fk_emails_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE emails ADD CONSTRAINT fk_emails_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE user_email_settings ADD CONSTRAINT fk_user_email_settings_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE user_email_settings ADD CONSTRAINT fk_user_email_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE email_attachments ADD CONSTRAINT fk_email_attachments_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE email_attachments ADD CONSTRAINT fk_email_attachments_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE messages ADD CONSTRAINT fk_messages_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE messages ADD CONSTRAINT fk_messages_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE message_reactions ADD CONSTRAINT fk_message_reactions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE message_reactions ADD CONSTRAINT fk_message_reactions_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL;